"""
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten
pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
difference are pentagonal and D = |Pk − Pj| is minimised; what is the
value of D?

"""

pentagonalNumbers = list()
searching = True

def getPentagonalNumber( n ):
    print(n, len(pentagonalNumbers))
    while (n > len(pentagonalNumbers)):
        pentagonalNumbers.append( int( n*(3*n - 1)/2 ) )
    print(n, pentagonalNumbers)
    return pentagonalNumbers[n-1]

def testPentNum( r ):
    if r > 1:
        for i in range(1, r):
            print(getPentagonalNumber(i))

i = 1
while searching:
    a = getPentagonalNumber( i )
    for n in range(1,i):
        b = getPentagonalNumber( n )
        print(a,b)
    i+= 1
    if i > 3: searching = False
