"""
Triangle, pentagonal, and hexagonal numbers are generated by the
following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

## count by triangle numbers
## check against pent
## if passed, check against hex
## save number
## if greater than 40755, end

searching = True
answers = list()
bound = 40755
i = 1

def Triangle(n):
    return n*(n+1)/2

def PentCheck( n ):
    if n == 0: return False
    if n == 1: return True
    c = (0.25) - (8 * (-n))
    a = ( 0.5 + (c**.5) )
    if type(a) != complex:
        if (a/3).is_integer(): return True
    return False

def HexCheck( n ):
    if n == 0: return False
    if n == 1: return True
    c = (1) - (8 * (-n))
    a = ( 1 + (c**.5) )/4
    if type(a) != complex:
        if (a).is_integer(): return True
    return False

saftey = 1000

while searching:
    t = Triangle(i)
    if PentCheck(t) and HexCheck(t):
        print(t)
        answers.append( t )
        if t > bound: searching = False
    saftey-=1
    if saftey <= 0:
        print("short")
        searching = False
    i+=1

print(answers)
print(t)
